import './Goods/body/cart.css';
import './Goods/footer/footer.css';
import './Goods/body/goods.css';
import './main.css';
import './Goods/body/goodBar.css';
import './Goods/body/pagination.css';
import './Goods/body/settingsApp.css';
import './Goods/body/utils.css';
import './Goods/header/navbar.css'
import './About.css'
import './Login.css'
import './GoodPage.css'
import './Order.css'